apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-fernet-keys
data:
  0: |
    gX_0Q9aoItZFLcAt2PUyehhOYmAj7tjIYBBOn4-6Obg=
  1: |
    ahnThYC6p7ry453WuKPmzCC0RZor3aNGCNzQUCoS3Y8=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-credential-keys
data:
  0: |
    -WReYKofsT7fweEboVp4eNy4yknFPPYnKTaQWsMQCH0=
  1: |
    saTWUjnJ36zgJGptYcQB7tyq03LDtmMXAKHYFPEorcQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-config
data:
  keystone.conf: |
    [DEFAULT]
    log_dir = /var/log/keystone
    [application_credential]
    [assignment]
    [auth]
    [cache]
    [catalog]
    [cors]
    [credential]
    [database]
    connection = mysql+pymysql://keystone:k3yst0ne!@keystone-mysql/keystone
    [domain_config]
    [endpoint_filter]
    [endpoint_policy]
    [eventlet_server]
    [extra_headers]
    [federation]
    [fernet_receipts]
    [fernet_tokens]
    [healthcheck]
    [identity]
    [identity_mapping]
    [jwt_tokens]
    [ldap]
    [memcache]
    [oauth1]
    [oslo_messaging_amqp]
    [oslo_messaging_kafka]
    [oslo_messaging_notifications]
    [oslo_messaging_rabbit]
    [oslo_middleware]
    [oslo_policy]
    [policy]
    [profiler]
    [receipt]
    [resource]
    [revoke]
    [role]
    [saml]
    [security_compliance]
    [shadow_users]
    [token]
    provider = fernet
    [tokenless_auth]
    [totp]
    [trust]
    [unified_limit]
    [wsgi]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-keystone
  labels:
    app: openstack-keystone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstack-keystone
  template:
    metadata:
      name: openstack-keystone
      labels:
        app: openstack-keystone
    spec:
      containers:
      - name: openstack-keystone
        image: ghcr.io/rpt-openstack/docker-keystone:2024.2
        volumeMounts:
          - name: config
            mountPath: /etc/keystone/keystone.conf
            subPath: keystone.conf
            readOnly: true
          - name: fernet-keys
            mountPath: /etc/keystone/fernet-keys
            readOnly: true
          - name: credential-keys
            mountPath: /etc/keystone/credential-keys
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: keystone-config
        - name: fernet-keys
          configMap:
            name: keystone-fernet-keys
        - name: credential-keys
          configMap:
            name: keystone-credential-keys
---
apiVersion: v1
kind: Service
metadata:
  name: openstack-keystone
spec:
  selector:
    app: openstack-keystone
  ports:
  - port: 5000
    targetPort: 5000
