name: Publish Container Image

on:
  push:
    branches:
      - "2024.2"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_PAT}}

      - name: 'Build and push Docker image'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/rpt-openstack/docker-keystone:2024.2
